/*

	This file contains the data structure definition
	which holds the scanned lua-scripts in memory.

	@author 	swayam.raina
	@dated 		05.12.2019

 */


package cache



/*
	This data structure holds the resource script contents
	and labels them with the resource name
 */
type Cache map[string]string



/*
	This method returns the resource script contents
	given the resource name. This method can only be
	called on the instance object.
	Note that, application has to manage the cache
	instance generated by the 'processor'

	key:		resource name
	return:		resource content
 */
func (cache *Cache) Get (key string) string {
	return (*cache)[key]
}


/*
	This method stores the resource script  contents
	in the cache object coressponding to the resource
	name.
	Note that, application has to manage the cache
	instance generated by the 'processor'

	key: 		resource name
	value: 		resource content
 */
func (cache *Cache) Set (key string, value string) {
	(*cache)[key] = value
}